### ISSUE TITLE
Define a way for provider locations to be specified

### ISSUE THREAD

**Issue by fershad** [thegreenwebfoundation/carbon.txt#20]
There are cases when one might use a provider's service in just one or a couple of regions. For example, you might use Object Storage services from Provider X, but only provision those services in that provider's `us-east` location.

In the current carbon.txt specification, there is no way to capture this detail. To provide more granularity and transparency through carbon.txt, there should be a method through which implementors can specify the provider regions they use as part of their service.

**Comment by fershad** [comment]
One proposal is to allow this to be included as an array for a provider. For example, the key of `region` can be set with an array of strings identifying the regions used.

```toml
[upstream]
providers = [
	{ domain='amazon.com', service='object-storage', regions=['us-east-1', 'eu-east-2'] }
]
```
